port: 8080
db:
    mongodb:
        -   enabled: true
            host: 127.0.0.1
            port: 27017
            username: gzulian
            password: test
            database: tef_nwm_test
            nameconn: connMongo
            lang: ES
    pgsql:
        -   enabled: true
            host: tef-nwm-test.cabpdjctpeks.us-east-1.rds.amazonaws.com
            port: 5432
            username: postgres
            password: mVC0vq3Iu4TiHbySVlkB
            database: tef-test
            nameconn: connPgsql
            lang: ES